#!/usr/bin/expect -f

# Markdown are placed inside Q's block comment.
# q code blocks inside Markdown will be executed.
# When exits from block comment, output ~~~q, and output ~~~ before enter block comment or exit file.

# a multiple line function start with an id : { [...] /comments
spawn q 
expect "q)"

set tmpf [open "/tmp/qnote.q" w]
set fp   [open [lindex $argv 0] r]
# TODO: multiple line function
puts "~~~q"
set state code

foreach line [split [read $fp] "\n"] { 
    switch -regexp $line {
        {^~~~[ ]*$}  -
        {^/[ ]*$}    { puts "~~~" ; set state comment }
        {^~~~q[ ]*$} -
        {^\\[ ]*$}   { puts "~~~q"; set state code    }
        {^\w+:\{$}   -
        {^\w+:\{.*]$} {
                        set tmpf [open "/tmp/qnote.q" w]
                        puts $tmpf $line; puts $line; flush $tmpf;
                        set state func }
        {^\    \}}   { if { $state eq "func" }  {
                           puts $tmpf $line
                           puts $line
                           flush $tmpf
                           send -- "\\l /tmp/qnote.q\r"
                           expect "\nq)"
                           set state code }}
        default      {
            if {$state eq "code" } {
                send -- "[string trim $line]\r"
                expect "\nq)"
            } elseif {$state eq "func"} {
                puts $tmpf $line
                puts $line
            } else {
                puts $line
            }
        }
    }
} 

close $fp
exit
