#!/usr/bin/expect -f
spawn q 
expect "q)"

set fp [open [lindex $argv 0] r]

# double comments + space are executed.
# single slash was removed in output. So you can put any markdown.
# beginning space removed because k interpretered it as comments.

set state code
foreach line [split [read $fp] "\n"] { 
    switch -regexp $line { 
        {^/[ ]*$}  { set state comment}
        {^\\[ ]*$} { set state code}

        {^// .*$} { 
            send -- "[string range $line 3 end]\r"
            expect "\nq)"
         }

        {^/.*}   { puts [string range $line 1 end] } 

        default {
            if {$state eq "code" } {
                send -- "[string trim $line]\r"
                expect "\nq)"
            } else { puts $line }
        } 
    }
} 

close $fp
exit
